### PR TITLE
Fix the failing Read the Docs

### PR DESCRIPTION
**Pull request by wtbarnes**
RTD build hasn't been built successfully in over a year. This *should* fix that.

* conda environment file greatly simplified
* no mathjax extension

Sphinx gallery still has some issues; I've not tried to fix these here.

### CODE REVIEW

**Comment by wtbarnes** [comment]
Err the 'build_sphinx' job still fails...not sure why Travis isn't catching that...

**Comment by wtbarnes** [comment]
@Alex-Ian-Hamilton @Cadair please review. Mostly minor changes, but some hacky stuff to get docs building.

I've bumped astropy-helpers to the latest version which seems to have fixed the strange sphinx failures (e.g.  [this log](https://travis-ci.org/sunpy/solarbextrapolation/jobs/218536683)). I've also had to pin sphinx to v1.5. Using the latest version (1.6.??) gives 2to3-looking errors (e.g. [this log](https://travis-ci.org/sunpy/solarbextrapolation/jobs/261405912)).

I've also skipped [this line of the doctest in `SeedStreamline`](https://github.com/sunpy/solarbextrapolation/blob/master/solarbextrapolation/mayavi_seed_streamlines.py) as I keep hitting [this error](https://travis-ci.org/sunpy/solarbextrapolation/jobs/261410673#L634). I don't have much experience with mayavi so maybe someone who does can spread a little light on this issue. Presumably, this best way to deal with this is not just to skip the test.

Added some info to the README as well.

**Comment by nabobalis** [comment]
If astropy helpers was updated to v2, I recall we were told to update ah_bootstrap.py and ez_setup.py via copying them directly from astropy_helpers.

**Comment by wtbarnes** [comment]
Hmm ok so maybe that would fix the 2to3 sphinx errors I was getting and we could unpin from v1.5

**Comment by wtbarnes** [comment]
@nabobalis thanks for the suggestion re: ah_bootstrap and ez_setup. That seems to fix the sphinx pinning problem.

**Review by Cadair — APPROVED** [review]

**Comment by wtbarnes** [comment]
Wow the RTD build actually passed on the first go. That's practically unheard of...

**Pull request merged**
